### ISSUE TITLE
Deobfuscate Error

### ISSUE THREAD

**Issue by Pairs34** [ErezAmihud/dearmor#11]
Hi , when I try this library on compiled exe from pyinstaller and get error.
Can u help me for this file ?
[yeni.zip](https://github.com/ErezAmihud/dearmor/files/10952050/yeni.zip)

**Comment by ErezAmihud** [comment]
Decompile the exe first

**Comment by ErezAmihud** [comment]
> Packaged with PyInstaller. I was able to do this. but I could not deobfuscate the main.pyc file.

Don't deobduscate main.pyc

Decompile it (with uncompyle6 pycdc or something similar) so that you have a .py file that you can run 
`python main.py` and it would work. The file would contain some lines that contain the word "pyarmor" and a big binary string, or aomething in that style.

 On that file use dearmor.

For example, see in the tests, run dearmor on obfuscated py files, not pyc.

If it would help you in any way, I previously had a "decompile" script in the repo https://github.com/ErezAmihud/dearmor/blob/31b550886dda6e74e5e1e1dcd1b9db3c701f639d/decompiler.py
It probably will not work out of the box

Good luck
